<?php

/**
 *  Remove sections from admin dashboard for everyone.
 *  
 *  In this case comment section
 * 
 *  https://developer.wordpress.org/reference/functions/remove_menu_page/
 */

function template_theme_edit_comment_menu()
{
    remove_menu_page('edit-comments.php');
}
add_action('admin_menu', 'template_theme_edit_comment_menu', 11);


/**
 *  With this code u can define which admin menu sections will be removed for users different from admin
 * 
 *  https://developer.wordpress.org/reference/functions/remove_submenu_page/
 * 
 *  https://developer.wordpress.org/reference/functions/remove_menu_page/
 * 
 */

if (!current_user_can('administrator')) {
    add_action('admin_menu', 'template_theme_edit_code_menu', 102);
    function template_theme_edit_code_menu()
    {
        remove_submenu_page('themes.php', 'theme-editor.php');
        remove_submenu_page('plugins.php', 'plugin-editor.php');
        remove_menu_page('options-general.php');
    }
}


/**
 *  Delete content which is automaticaly added by WordPress and we do not need
 *  
 *  https://developer.wordpress.org/reference/functions/remove_action/
 */

function template_theme_embeds_init()
{
    // Deleting support for Emogi
    remove_action('wp_head', 'print_emoji_detection_script', 7);
    remove_action('wp_print_styles', 'print_emoji_styles');

    // Deleting "Generated by WordPress" tag
    remove_action('wp_head', 'wp_generator');

    // Deleting RSS feed for blog
    remove_action('wp_head', 'feed_links_extra', 3);
    remove_action('wp_head', 'feed_links', 2);

    // Removes support for responsive embeds i've added in site settings
    // This is just for showcase
    wp_dequeue_script('wp-embed');

    // Deleting RSD link
    remove_action('wp_head', 'rsd_link');

    // Deleting REST API
    remove_action('wp_head', 'rest_output_link_wp_head');
    remove_action('wp_head', 'wp_oembed_add_discovery_links');
    remove_action('template_redirect', 'rest_output_link_header', 11);

    // Deleting WLW Manifest link
    remove_action('wp_head', 'wlwmanifest_link');

    // Deleting shortlink
    remove_action('wp_head', 'wp_shortlink_wp_head');
}
add_action('init', 'template_theme_embeds_init', 15);

/**
 *  Another removals with different hook
 */
function template_theme_extra_removals()
{

    // deactivate new block editor Widget and active old editor Widget
    remove_theme_support('widgets-block-editor');
}
add_action('after_setup_theme', 'template_theme_extra_removals');


// Remove feed icon link from legacy RSS widget.
add_filter('rss_widget_feed_link', '__return_false');
